[[main]]
name = "হোম"
pageRef = "/"
weight = 10

[[main]]
name = "গল্প"
pageRef = "/stories"
weight = 20

[[main]]
name = "উপন্যাস"
pageRef = "/novels"
weight = 25

[[main]]
name = "অপ্রকাশিত"
pageRef = "/unpublished"
weight = 30

[[main]]
  name = "স্মৃতির পাতা থেকে"
  pageRef = "/archive"
  weight = 35

[[main]]
name = "ভ্রমণকাহিনী"
pageRef = "/travelogue"
weight = 40

[[main]]
name = "চিত্রশালা"
pageRef = "/gallery"
weight = 50

[[main]]
name = "প্রবন্ধ"
pageRef = "/articles"
weight = 60