[[main]]
name = "Home"
pageRef = "/"
weight = 10

[[main]]
name = "Stories"
pageRef = "/stories"
weight = 20

[[main]]
name = "Novels"
pageRef = "/novels"
weight = 25

[[main]]
name = "Unpublished"
pageRef = "/unpublished"
weight = 30

[[main]]
  name = "From the Archives"
  pageRef = "/archive"
  weight = 35

[[main]]
name = "Travelogue"
pageRef = "/travelogue"
weight = 40

[[main]]
name = "Gallery"
pageRef = "/gallery"
weight = 50

[[main]]
name = "Articles"
pageRef = "/articles"
weight = 60