[[main]]
name = "Home"
pageRef = "/"
weight = 10

[[main]]
name = "Stories"
pageRef = "/stories"
weight = 20

[[main]]
name = "Unpublished"
pageRef = "/unpublished"
weight = 30

[[main]]
name = "Publications"
pageRef = "/publications"
weight = 40

[[main]]
name = "Gallery"
pageRef = "/gallery"
weight = 50

[[main]]
name = "Articles"
pageRef = "/articles"
weight = 60

[[main]]
name = "Language"
weight = 100
identifier = "language-switcher"
[main.params]
action = "locale"
