baseURL = 'https://www.bhowmickarchives.in/'
title = 'Complete Works of Aparesh Bhowmick'
theme = 'congo'
defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Complete Works of Aparesh Bhowmick"
    contentDir = "content/english"
    [languages.en.params]
      [languages.en.params.author]
        name = "Aparesh Bhowmick"
      description = "The complete works of Aparesh Bhowmick."
  [languages.bn]
    languageName = "বাংলা"
    weight = 2
    title = "অপরেশ ভৌমিকের সমগ্র রচনা"
    contentDir = "content/bengali"
    [languages.bn.params]
      [languages.bn.params.author]
        name = "অপরেশ ভৌমিক"
      description = "অপরেশ ভৌমিকের সমগ্র রচনা।"